parameters:
- name: AdditionalPlatforms
  type: object
  default: []
- name: PreSteps
  type: object
  default: []
- name: PostSteps
  type: object
  default: []
- name: EnvVars
  type: object
  default: {}
- name: MaxParallel
  type: number
  default: 0
- name: BuildInParallel
  type: boolean
  default: true
- name: TimeoutInMinutes
  type: number
  default: 60
- name: Location
  type: string
  default: ''
- name: TestCanary
  type: boolean
  default: false
- name: ServiceDirectory
  type: string
  default: not-specified
- name: TestSetupSteps
  type: stepList
  default: []
- name: Clouds
  type: string
  default: 'AzureCloud'

stages:
  - template: ./archetype-sdk-tests-clouds.yml
    parameters:
      Location: ${{ parameters.Location }}
      AdditionalParameters:
        PreSteps: ${{ parameters.PreSteps }}
        PostSteps: ${{ parameters.PostSteps }}
        EnvVars: ${{ parameters.EnvVars }}
        MaxParallel: ${{ parameters.MaxParallel }}
        BuildInParallel: ${{ parameters.BuildInParallel }}
        TimeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
        ServiceDirectory: ${{ parameters.ServiceDirectory }}
        TestSetupSteps: ${{ parameters.TestSetupSteps }}
      Platforms: 
        ${{ each platform in parameters.AdditionalPlatforms }}:
          ${{ platform.key }}: ${{ platform.value }}
        Linux_NetCore:
          DisplayName: "Test on Linux"
          OSVmImage: "ubuntu-18.04"
          TestTargetFramework: netcoreapp2.1
          PreSteps:
            - template: /eng/common/pipelines/templates/steps/bypass-local-dns.yml
        Windows_NetCore:
          DisplayName: "Test on Windows for NetCoreApp"
          OSVmImage: "windows-2019"
          TestTargetFramework: netcoreapp2.1
        Windows_NetCore_ProjectRefAzureClients:
          DisplayName: "Test on Windows for NetCoreApp with UseProjectReferenceToAzureClients=true"
          OSVmImage: "windows-2019"
          TestTargetFramework: netcoreapp2.1
          AdditionalTestArguments: /p:UseProjectReferenceToAzureClients=true
        Windows_NetFramework:
          DisplayName: "Test on Windows for .Net Framework"
          OSVmImage: "windows-2019"
          TestTargetFramework: net461
        Windows_NetFramework_ProjectRefAzureClients:
          DisplayName: "Test on Windows for .Net Framework with UseProjectReferenceToAzureClients=true"
          OSVmImage: "windows-2019"
          TestTargetFramework: net461
          AdditionalTestArguments: /p:UseProjectReferenceToAzureClients=true
        MacOS:
          DisplayName: "Test on MacOS"
          OSVmImage: "macOS-10.15"
          TestTargetFramework: netcoreapp2.1
          SupportedClouds: 'AzureCloud'
        Windows_NetCore_Record:
          DisplayName: "Record on Windows for NetCoreApp"
          OSVmImage: "windows-2019"
          TestMode: Record
          TestTargetFramework: netcoreapp2.1
          AdditionalTestArguments: /p:AutoUpdateSessionRecords=true
          PostSteps:
            - task: CopyFiles@2
              displayName: "Copy Test Recordings"
              inputs:
                sourceFolder: '$(Build.SourcesDirectory)'
                contents: 'sdk/${{ parameters.ServiceDirectory }}/**/SessionRecords/**/*.json'
                targetFolder: '$(Build.ArtifactStagingDirectory)/SessionRecords'
            - task: PublishBuildArtifacts@1
              displayName: "Publish Test Recordings"
              inputs:
                pathToPublish: '$(Build.ArtifactStagingDirectory)/SessionRecords'
                artifactName: SessionRecords
          SupportedClouds: 'AzureCloud'
